"""
Django settings for vasconsellos project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # type: ignore
from supabase import create_client, Client  # type: ignore

# --------------------------------------------------------
# BASE PATHS Y VARIABLES DE ENTORNO
# --------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar archivo .env
load_dotenv(BASE_DIR / ".env")

# --------------------------------------------------------
# VARIABLES DE CONFIGURACIÓN DE SUPABASE
# --------------------------------------------------------
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# Crear cliente de Supabase (para API, auth, storage, etc.)
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# --------------------------------------------------------
# CONFIGURACIÓN DJANGO
# --------------------------------------------------------

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-#2#2(w6hsf&^oz$hgo+1s&+(tkm2m9-z@%(_%o7x&$yp+3wa^v"  # valor por defecto
)

DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = ["*"]

# --------------------------------------------------------
# APLICACIONES INSTALADAS
# --------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# --------------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vasconsellos.urls'

# --------------------------------------------------------
# TEMPLATES
# --------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vasconsellos.wsgi.application'

# --------------------------------------------------------
# BASE DE DATOS (SUPABASE POSTGRESQL)
# --------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("SUPABASE_DB"),
        "USER": os.getenv("SUPABASE_USER"),
        "PASSWORD": os.getenv("SUPABASE_PASSWORD"),
        "HOST": os.getenv("SUPABASE_HOST"),
        "PORT": os.getenv("SUPABASE_PORT", "6543"),
    }
}

# --------------------------------------------------------
# VALIDACIÓN DE CONTRASEÑAS
# --------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------------------
# CONFIGURACIÓN REGIONAL
# --------------------------------------------------------
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------------
# ARCHIVOS ESTÁTICOS
# --------------------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# --------------------------------------------------------
# CONFIGURACIÓN DE CLAVES PRIMARIAS POR DEFECTO
# --------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
